# Generated by Django 5.0 on 2024-04-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
