# Generated by Django 5.0 on 2024-04-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_remove_patient_phonenumber_remove_patient_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
