# Generated by Django 5.0 on 2024-04-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
