# Generated by Django 5.0 on 2024-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DemoApp', '0007_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=15)),
                ('PhoneNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('PaymentType', models.CharField(max_length=15)),
            ],
        ),
    ]
