# Generated by Django 5.0 on 2024-04-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
