# Generated by Django 5.0 on 2024-05-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0011_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
    ]
