# Generated by Django 5.0 on 2024-05-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0013_alter_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='medicine',
            new_name='medicine_name',
        ),
    ]
