# Generated by Django 5.0 on 2024-05-05 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0014_rename_medicine_invoice_medicine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='DemoApp.patient'),
        ),
    ]
