# Generated by Django 5.0 on 2024-05-06 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0016_remove_invoice_id_alter_invoice_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
