# Generated by Django 5.0 on 2024-05-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.CharField(max_length=20),
        ),
    ]
