# Generated by Django 5.0 on 2024-05-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0019_alter_invoice_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
