# Generated by Django 5.0 on 2024-05-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DemoApp', '0020_delete_invoice_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('PaymentType', models.CharField(max_length=15)),
                ('Acceptance', models.CharField(max_length=15)),
            ],
        ),
    ]
